### PR TITLE
README: Update requirements

### PR DESCRIPTION
**Pull request by notcarbide**
- Add grunt-cli
- Add php requirements

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your contribution. 

I suggest a modification to the build script to use `node_modules/.bin/grunt` instead of requiring the install of `grunt-cli` globally.

**Comment by notcarbide** [comment]
I see. So rather require npm?

**Comment by NicolasCARPi** [comment]
`yarn` is used instead of `npm`.

**Comment by notcarbide** [comment]
Ahh got it now after actually looking into how it builds and reading up a bit on yarn.
I'm curious as to why grunt is used directly in the script instead of the link in node_modules. Should my environment already have .bin in path?

**Comment by NicolasCARPi** [comment]
Yes, I have the node_modules/.bin in my $PATH. But this is why I suggest to change the line in the script. I can merge it like that and do it myself or you can do it by adding a commit.

**Pull request merged**
